### ISSUE TITLE
issues collections from schackartk (solved)

### ISSUE THREAD

**Issue by schackartk** [KennthShang/PhaMer#1]
Hi! Thank you for publishing your code publicly.

I am a researcher who works with many tools that identify phage in metagenomes. However, I like to be confident in the implementation of the concepts. I noticed that your repository does not have any formal testing. Without tests, I am always skeptical about implementing a tool in my own work because I cannot be sure it is working as described.

Would your team be interested in adding tests to the code (_e.g._ using `pytest`)? If I, or another developer, were to create a pull request that implemented testing, would your team consider accepting such a request?

Also, it is a small thing, but I noticed that your code is not formatted in any community-accepted way. Would you consider accepting a pull request that has passed the code through a linter such as `yapf` or `black`? I usually add linting as part of my test suites.

**Comment by KennthShang** [comment]
Hi,

I think maybe you miss some descriptions in the guidelines. There is a test with a given test file. Maybe I should emphasize it.

Anyway, thanks for your suggestions

**Comment by schackartk** [comment]
Thanks for the reply. I understand that you provide an example file, but that is not the same as providing tests.

Tests are programs that run your propram and ensure that is behaves as expected. For instance, you would have unit tests that ensure that when functions are given certain inputs, they return the expected output. You would have integration tests that test that if a certain input file is given to the program, the correct output files are created containing the expected results.

By giving an example file, the user has to check themselves that the output is created. And we (the user) cannot be sure what the contents of the output file should be. Tests would formalize this by explicitly stating what the output should be so the user doesn't have to verify it theirself.

**Comment by KennthShang** [comment]
The format of the output file is in the guidelines which is enough for users to check whether the program is running correctly. 

Like many other program, we do not have and cannot support additional log files. If users have any problems when using the program, we will reply them in time.

Best,
Jiayu

**Comment by KennthShang** [comment]
By the way, the program has been tested several times on different systems. Thus, it should be ok if the users can follow the guidelines to install and use it.

**Comment by schackartk** [comment]
Seeing the output file is there is not enough though. For instance, how do I know that the rejection threshold is being properly implemented? Or how can you, the developers, refactor or add features while being assured that previous functionality has not been broken without tests? This also makes open source contribution tricky, since others cannot be sure their contributions are not breaking functionality.

Also as pointed out in #2, the program does not work as described on my system. Testing could help prevent this.

**Comment by KennthShang** [comment]
This seems really strange that you do not want to follow the guidelines to install and active your python3 environment to run the code. Then stating that they are caused by the program.

**Comment by schackartk** [comment]
I do have Python 3 active and installed. I also have Python 2 installed. In most cases where both are installed `python` points to Python 2 while `python3` points to Python 3.

**Comment by KennthShang** [comment]
However, if you have activate the conda environment as shown in guidelines, python will only point to python3.

If you have tested all other phage detection tools like seeker, deepvirfinder, virsoter, the first thing you need to do is to activate the environment. Our method has followed the same rules as others

**Comment by KennthShang** [comment]
Hi @schackartk, I'd like to summarize all your comments and issues in this one for a better view for other users. Since I am on my holidays. The previous comments are replied with my phone and they might not be formal. Sorry for the late updates.


**Some minor issues:**
We are very grateful for your suggestions. In the new version, we add the argparse documentation. Also, the program will generate a folder to store the output files if the folder does not exist.


**Some major issues:**

1. **For the questions in this issue**:
There are no more 'test files' for the program currently. Since the paper is still under review, we will not change anything to ensure the experimental results can be repeated. Also, it seems all other methods do not have the function you mentioned if you can provide a link showing how to add them, I'd like to revise the code according to your needs. Currently, we are also pleased if you want to revise your local version. And if you have further questions, we will reply to you on time.


2. **For the second issue "cannot run Phamer with `./PhaMer.py --contigs input.fa`" and the problems you mentioned in this issue "cannot run PhaMer with `python PhaMer.py --contigs input.fa`":** 
We do recommend users follow what the guidelines show to run PhaMer. This is because we think rather than solving any potential bugs, users may prefer to run the code only to provide the input files. As you mentioned "users are lazy", directly copying the command lines mentioned in the guidelines will be more suitable. Another question that you mentioned is that `python PhaMer.py --contigs input.fa` does not work on your systems. This is because you need to activate the phamer environment as mentioned in the manuscript like "conda activate phamer" or "source activate phamer". We followed the same rules as many other tools like *seeker*, *deepvirfinder*, and *virsoter* to make sure the environment can be launched. Since we have tested the program serval times on different systems, following the guidelines will ensure all the users run the code correctly. We are pleased if anyone wants to revise the code locally, however, if your local version has new bugs, I'm sorry that we may not provide any helps.

3. **For the third issue "Force removal of my directory"**
The program will generate/replace the folder `output/` to store the intermediate files. We are really sorry if you happen to have a folder with the same names. Now, we change the name for that folder to `phamer/` to avoid the problem and we have emphasized this in the guidelines. Another suggestion for you is to generate a new folder to run new programs. This is because programs often generate/remove intermediate files. Although some of the users might want to add the program to their $PATH, few of them will run the program under a folder where they store their *very important files*. BTW we **do not** state that PhaMer can be run as a binary file. In the guidelines, we only show how to run within the GitHub folder. So, if you have any problems/uncertainties, maybe you should ask us first.  Otherwise, we cannot provide any helps if users have their own minds to use the revised local version.


Best,
Jiayu

**Comment by schackartk** [comment]
Hello Jiayu,

I genuinely appreciate that you are taking the time to address user issues. I have pulled your recent changes.

**Minor Issues**
The addition of argument help messages is useful. I do notice however that the general argparse message is still "manual to this script" instead of describing the program(s). I also see that you can create non-existent output directories which is very helpful.

**Major issues**
1. **No tests**
I have also noticed that most small bioinformatics tools do not use proper testing. An example of some minimal testing can be seen in my fork of MetaPhinder. For instance there is the [integration test file](https://github.com/schackartk/MetaPhinder/blob/initial-rework/tests/MetaPhinder_test.py) and unit tests within [the program itself](https://github.com/schackartk/MetaPhinder/blob/initial-rework/MetaPhinder.py). These can be critical. For instance, MetaPhinder described an equation in their paper, but the implementation in code did not return the correct results. By adding the unit test `test_calc_rel_mcov()`, I can verify that my updated version of their equation in code, which I gave its own function, returns the right value.
You can add tests without changing the functionality of your code. In fact it would just make sure that your features are working properly. For instance, to integrate the changes suggested by my other issue in which you can now create output in a new directory: you would first write a test checking that trying to write to a non-existent directory fails, then you would update the code to add the new feature (as you did), then you would verify that the test now passes.

2. **No shebang**
My apologies, I got confused on the installation instructions regarding setting up the conda environment. I have redone it and can verify that running the commands as described works for me.
However, if you would like to make it possible to run the program without first typing "python" you can add a shebang line to your files as the first line of each program (`#!/usr/bin/env python3`). This is common and can be seen in [DeepVirFinder](https://github.com/jessieren/DeepVirFinder/blob/master/dvf.py) and [VirSorter](https://github.com/simroux/VirSorter/blob/master/wrapper_phage_contigs_sorter_iPlant.pl). To be clear, it will not affect how you currently run it. You can still type `python` first with no problem. But if you make it executable (`chmod +x PhaMer.py`), then it can be run directly (`./Phamer.py`). To be clear, this is not converting it to a binary, it just tells the system what to use for execution.
This is a feature request not a bug though.

3. **Force removal of my directory**
Making the temporary folder `phamer/` seems a little safer, but it still makes it impossible to run the tool concurrently. To do so, I would need an installation of the tool and databases for each sample, which is impractical when you need to run many at the same time.
To be clear, some other tools have the same problem due to writing to the same intermediate file folder. Of note [DeePhage](https://github.com/shufangwu/DeePhage) is the same way and their README states " If you want to run multiple tasks at the same time (either on physical host or virtual machine), please copy DeePhage package into different folders and run different tasks under different folders. Do not run different tasks under the same folder.". For this reason, I can not use such tools.
Since this is a common challenge, there are packages dedicated to avoiding it, such as [tempfile](https://docs.python.org/3/library/tempfile.html). 

Again, thank you for taking the time to address the problems. Also, have you removed the closed issues? It can be nice to keep them so we can reference them still, or if I am making a mistake in my usage, others can see your proposed solutions.

Best,
-Ken

**Comment by KennthShang** [comment]
Thanks for your further suggestions. We will revise the code accordingly.

Best,
Jiayu

**Comment by KennthShang** [comment]
The second and the third major issues should be solved. I added a new option to choose the folder to store the intermediate files so the program can be run concurrently.

Updates: I have solved some small bugs caused by editing the code with my phone. Sorry for that if they bring you trouble.

Best,
Jiayu
