### ISSUE TITLE
Can you provide the training code of model? Thanky!

### ISSUE THREAD

**Issue by junzai0215** [KennthShang/PhaMer#10]
I copied your test code and changed it to the training code, but nan values appear during training process in the gpu environment you specified. Do you meet this problem? Beyond that, the positional embedding is a fixed value, or is it learned during the training process? And are there any trick in the training process? 

Sincerely hope that you can provide the training code. Thank you very much!

**Comment by KennthShang** [comment]
Are you working on the phage identification problem? Can you check whether your input is correct?

**Comment by KennthShang** [comment]
If you are working on phage identification, you need to generate short contigs as mentioned in the manuscript. For example, the current version of PhaMer is trained on phages released before Dec. 2018. We used this training set to generate 3kbp, 5kbp, 10kbp, and 15kbp segments and trained the model with the complete genomes. If you want to benchmark, you can use the code directly with the same dataset. If you want to re-train the model, please also generate short contigs. This is because if the model is only trained on the complete genomes, PhaMer will have low recall on the short contigs.

If you are not working on the phage identification problem, then the model cannot be trained. BTW, both embedding are learned by the model and I have no idea about the nan values.
