### ISSUE TITLE
bioconda recipe 

### ISSUE THREAD

**Issue by nick-youngblut** [KennthShang/PhaMer#12]
Any plans on creating a bioconda recipe for PhaMer? That would greatly help users with the install & version management of PhaMer.

Also in regards to:

>Because the parameter is larger than 100M, please make sure you have downloaded transformer.pth correctly.

Why not just use md5sum?

**Comment by KennthShang** [comment]
Thanks for your suggestions. But maybe it is not necessary currently because we do not have many updates for the program. The future updates might be the database/parameters I suppose. Also, it seems using bioconda recipe won't save much time or reduce the progress of installing PhaMer. Using PhaMer.yaml directly might be much easier for new users. We might consider this when it is necessary.

Also, thanks for the suggestion of using md5sum. I have added such notice in README.

Best,
Jiayu
