### ISSUE TITLE
Phamer predicts nothing using real dataset.

### ISSUE THREAD

**Issue by Sanrrone** [KennthShang/PhaMer#15]
Dears,
Using the set number 4 of this publication https://www.frontiersin.org/articles/10.3389/fmicb.2023.1078760/full
Phamer predicts nothing, all results are non-phage with 0 score. I think it should be a training issue?, how can I train my own model? I would like to use not only refseq db.

thanks in advance!

**Comment by KennthShang** [comment]
Thanks for using our tools.

This issue might be caused by the strict threshold default in PhaMer: --reject 0.3. You can try --reject 0 so that PhaMer can identify more novel/diverse phages.

The suggested (default) value of --reject=0.3 is determined from large-scale metagenomic data with wet experiments verification to reject prophage or false positive. It is hard to say whether it is caused by the dataset or the methods. But if you wish to predict more novel phages, the smaller the value the higher the recall. By the way, you may also need to adjust the --len according to your needs.

Best,
Jiayu

**Comment by Sanrrone** [comment]
The dataset is divided into 2 "assemblies", raw assemblies and bins (a more scaffolded assembly), If I use assemblies instead of bins, works nicely, but It detects nothing from bigger contigs (as the bins). 
In order to reproduce the behavior I bring a case, I uploaded a single contig which other tools tag as viral (bin.13.zip)

command:
```
python $SDIR/PhaMer_preprocessing.py --dbdir $SDIR/database --contigs bin.13.fa --threads 16 --len 0
python $SDIR/PhaMer.py --dbdir $SDIR/database --threads 16 --out test.csv --reject 0
```
output:
```
Contig,Pred,Score
SAMEA2467085-ContigCoA-k109_69582,non-phage,0.0
```
and same file using other tool, for example DeepVirFinder
```
name	len	score	pvalue
SAMEA2467085-ContigCoA-k109_69582	274114	0.8355975151062012	0.02254702016768638
```
This is just one example of thousand bins with 0 score, I could understand the difference between scores, or even if we are on a false positive/negative case, but I cannot understand why I am not getting any prediction > 0.
Curiously, as I said before, using assemblies it works. perhaps contigs should be not so big?
in any case, I would like to know, how can I train my own model? do you have some tutorial?

thanks in advance!
[bin.13.zip](https://github.com/KennthShang/PhaMer/files/10931479/bin.13.zip)

Edit: the example belong to a bacteria (I used kraken2), so it is highly possible that this case in particular being a false positive of the other tools and phamer is right to classify it with 0, or we are talking about a prophage or ... etc. I am still confused about why all bins are 0.

**Comment by KennthShang** [comment]
Theoretically, the length/distribution of the proteins are learned by PhaMer. To be simple, you can imagine that if a seqeunce contain a large number of proteins but few of them belong to phage proteins (or less confident phage proteins), the model will reject them. But remember that this is an simple way to explain the model (I suppose). More computational logic behind the model itself, such as leanring the protein-protein association.

In your problem: bins are rejected but contigs are fine. To be simple, this is might be because some of the contigs has contains more confident phage proteins, then this sequences has larger chance to be  predicted as phages. I use the PhaBOX (our webserver) to visualize the low confidence results as below. If the top-left is a seperate contig, then it might be predicted as phage I supppose.

<img width="601" alt="image" src="https://user-images.githubusercontent.com/22445402/224035887-231e8ac2-d925-4f77-b5a5-aa06ec51764c.png">

Back to your problem: training the model. You can use the pre_process script to generate the 'sentence'(in the mid file), then use the sentence to train the model. You only need to add some train function in PhaMer.py, which is the same as all other deep learning method. Some tutorial can be found via: https://pytorch.org/tutorials/beginner/introyt/trainingyt.html

**However, we strongly do not suggest you to train a customized model**. This is because there are much more thing you need to do to train a good model for metagenomic data. For example, you need to select hard cases (host of the phages) to be the negative set. You need to balance your data. You need to tunning the hyperparameters based on your new training set. And also you need to genrate short segments to handle the length range of the poteintial inputs sequences. Although the current model has only been trained on RefSeq, it has the overall good performance on short contigs, mock data, metagenomic data, and several large database such as genbank and IMG/VR. 

Best,
Jiayu

**Comment by KennthShang** [comment]
BTW, I am curious how did you combine the contigs into bins? It seems there is no 'N' in the FASTA file. Did you directly concate them together? As I know, the binning tools will only group contigs into one file rather than combine them into one sequence.

Best,
Jiayu

**Comment by Sanrrone** [comment]
thanks you very much! it is more clear now.
Regarding the bins, I did not perform the assembly but citing the paper that I am trying to replicate:

>reads were assembled using Megahit v[1](https://www.frontiersin.org/articles/10.3389/fmicb.2023.1078760/full#footnote1).2.9. The code of the pipeline used for the assembly is available on Github.1 Megahit was run on the paired-end reads or single-end reads using the default parameters (referred to as the simple assembly). Additionally, a co-assembly of the multiple runs per BioSample was also performed (referred to as the co-assembly). Assemblies were binned with MetaBAT 2 v2:2.15
>[1] https://github.com/aponsero/Assembly_metagenomes

**Comment by KennthShang** [comment]
Good to know.

Best,
Jiayu
