### ISSUE TITLE
Force removal of my directory

### ISSUE THREAD

**Issue by schackartk** [KennthShang/PhaMer#5]
As mentioned in #4 , the user cannot choose the output directory. But far more concerning is that the tool **force removes** the output directory without any warning.

If I have an output directory like this:

```
$ ls output
very_important_files/  my_research/ 
```

Then once I run your tool, all my files have been deleted:
```
$ ls output
database.dmnd  filtered_contigs.fa  results.abc  results.tab  test_protein.fa
```

Even if I only use the root of this repo for running the tool, then if I run the tool for one metagenome, then run it for another, all the results from the first run are deleted.

A program should **never** do `rm -rf`, especially without warning.

**Comment by KennthShang** [comment]
The program currently should be run within the GitHub folder. I am sorry for the inconvenience. We emphasize this and will update it soon.

**Comment by schackartk** [comment]
Thank you for the response. Can we please keep this issue open until this problem is resolved? This is a critical problem with how the program functions currently. I want to be sure that any potential users are wary of it until then.

**Comment by schackartk** [comment]
I understand that the tool should be run from within the repository, but the folder name "output" has nothing special about it. If someone is using your tool, they certainly may store files in a folder named *output*. Or perhaps they may clone the repo and add it to their `$PATH` to be used elsewhere. In both cases, you risk permanently deleting a users folder if there happens to be one named *output* where they are running your tool.

**Comment by KennthShang** [comment]
I have added the description in the guidelines stating that do not use the same name ''output" to store the data since it will be used to store intermediate files.

Another suggestions for you is to use the GitHub folder only as an environment to run the code. Many programs will output intermediate file without warning, since the authors may not be aware of all the situations. 

However, we will revised the program according to any needs and we are really sorry if the program bring you trouble.

Best,
Jiayu
