### ISSUE TITLE
help, please answer these questions, thank you very much!

### ISSUE THREAD

**Issue by junzai0215** [KennthShang/PhaMer#9]
Can you briefly describe what these midfiles generated by 'preprocessing.py' mainly contain? In addition, where are the corresponding variables of protein-cluster embedding and positional embedding input by Transformer block? Where is the two embedding layers for dimensionality reduction to the two embeddings? 

![image](https://user-images.githubusercontent.com/75667816/156186617-7b210de0-d270-4a46-9e53-29c68024b85a.png)

**Comment by KennthShang** [comment]
Hi,

sentence: generated protein cluster sentences for each input contigs. (you can find it in the paper. Although the paper has not been published yet, you can find the arxiv version)
id2contig: corresponding index (row) in the sentence. It is used to generate predictions for each input contigs.
proportion: proportion of the protein clusters on each contig.
pc2wordsid: dictionary used to convert protein cluster (string type) into numerical type.

I do not know what do you mean by the "protein-cluster embedding and positional embedding input by Transformer block". I think you refer to the output of the embedding layer in the Transformer? They will not output by the program because PhaMer is designed to predict for contigs. However, they are accessible if you are familiar with Pytorch since the model will generate outputs for each step in the Transformer. If you check the model.py, you will find the structure for both PC embedding and POS embedding. They are the same as the original Transformer model.

By the way, there is no 'dimensionality reduction' operation in the Transformer. I suppose you refer to the one-hot encoding vs. embedding layer. You can also find them in the [Transformer paper](https://arxiv.org/abs/1706.03762)

Best,
Jiayu

**Comment by junzai0215** [comment]
> sentence means the sequence consisted of protein-cluster id, that is protein-cluster embedding?
id2contig means the positional embedding?
the proportion is the what's the function of proportion? this proportion is the ratio of successfully matched protein cluster numbers with the protein cluster dictionary length on each contig? 

I want to know where is the corresponding variable of protein-cluster embedding and the corresponding variable of positional embedding in code. As shown in the figure below, these embeddings were be input to Transformer block and I don't find the two embedding layers in code, please tell me, thanky!
![1646185558(1)](https://user-images.githubusercontent.com/75667816/156281201-bc0a862e-eb84-4391-a790-8e24c7164f16.png)
![1646185612(1)](https://user-images.githubusercontent.com/75667816/156281212-88764af6-ebad-439d-a058-f193084df0dc.png)

**Comment by KennthShang** [comment]
As I mentioned in the last response, they are in the model.py

<img width="679" alt="image" src="https://user-images.githubusercontent.com/22445402/156292345-be80e653-2c3b-4f53-a1cc-5f9afd5efc2d.png">

**Comment by junzai0215** [comment]
thanks for your replying in time! 

1.The proportion is the ratio of successfully matched protein cluster numbers with the protein cluster dictionary length on each contig? 

2.What's the function of "def reject_prophage(all_pred, weight)"? If the proportion value is low, it will be judged the negative sample.

**Comment by junzai0215** [comment]
"proportion and the reject_prophage are used to reject prophage, which is also a type of phages but integrase their genomes on the bacterial genomes."

thanky, It seems to be not mentioned in paper.

**Comment by KennthShang** [comment]
The paper is not published yet and the paper on the arxiv is just the manuscript. The proportion is used for biologists to design whether they prefer to predict prophage as phage or **only** predict for the phage contigs.

**Comment by junzai0215** [comment]
thank you very much!

**Comment by junzai0215** [comment]
There seems to be no code for training the model PhaMer？

**Comment by KennthShang** [comment]
Because the PhaMer is designed for phage identification, there is no train script uploaded to this GitHub currently. However, The model is implemented using Pytorch and has the same function to be trained.

**Comment by junzai0215** [comment]
Can you provide the training code of model so that we can train the model by ourselves? Thanky!

**Comment by junzai0215** [comment]
The positional embedding is a fixed value, or is it learned during the training process of the model? I copied your test code and changed it to training code, but nan values often appear during training process. Are there any trick in the training process? Sincerely hope you can provide the training code to me . Thank you very much!
